### PR TITLE
Add approve timesheet activity to android app, refactor activities

### PR DESCRIPTION
**Pull request by erjohnson**

### CODE REVIEW

**Comment by jerriep** [comment]
When I select the Approve option the app just crashes:

screen shot 2017-09-13 at 12 18 38 pm

No idea why.... At the very least add some exception handling so we can try and figure out what is happening here

**Comment by jerriep** [comment]
@erjohnson I left some comments. Please address

**Comment by jerriep** [comment]
@erjohnson  Given Maria's discussion at the standup, I think you should actually change that back again from `auth0_tenant` to `auth0_domain`. 

Not sure why you changed it in the first place?

**Comment by erjohnson** [comment]
Yea I changed it back based on the discussion.

**Comment by jerriep** [comment]
Looking great @erjohnson !

**Pull request merged**
